

	LDI	R20,HIGH(RAMEND)
	OUT	SPH,R20
	LDI	R20,LOW(RAMEND)
	OUT	SPL,R20			

	LDI	XH,HIGH(COUNTER)
	LDI	XL,LOW(COUNTER)	
	CALL	LOAD_FROM_EEPROM	
	INC	R20				
	CALL	STORE_IN_EEPROM	
HERE:
	RJMP	HERE	

LOAD_FROM_EEPROM:
		SBIC	EECR, EEWE
		RJMP	LOAD_FROM_EEPROM	
		OUT		EEARH,XH		
		OUT		EEARL,XL			
		SBI		EECR,EERE			
		IN		R20,EEDR			
		RET

STORE_IN_EEPROM:
		SBIC	EECR, EEWE
		RJMP	STORE_IN_EEPROM		
		OUT		EEARH,XH		
		OUT		EEARL,XL			
		OUT		EEDR,R20
		SBI		EECR,EEMWE			
		SBI		EECR,EEWE			
		RET

.ESEG
.ORG	0
COUNTER:	.DB	0
